-- INSERTO LOS ROLES POR DEFECTO QUE VAN A TENER LOS USUARIOS QUE SE LOGUEEN
INSERT INTO ROLES (NAME) VALUES('USER');
INSERT INTO ROLES (NAME) VALUES('ADMIN');

-- INSERTO ALGUNOS USUARIOS POR DEFECTO
INSERT INTO USERS (USERNAME,PASSWORD,EMAIL)
    VALUES ('tiki','pepi90','thiago@gmail.gov');

INSERT INTO USERS (USERNAME,PASSWORD,EMAIL)
    VALUES ('estipy','rabasedas2021','esteban@gmail.edu');

INSERT INTO USERS (USERNAME,PASSWORD,EMAIL)
    VALUES ('admin','admin','example@example.cpp');

---- INSERTO PRODUCTOS PARA PROBAR
INSERT INTO DRESS (SUBCATEGORY,SEX,BRAND,MODEL,CODE,STOCK,PRICE,AGE,SIZES,COLOR,ENABLED)
    VALUES ('remeras','hombre','nike','A','AB045BA',TRUE,2900,'adultos','20','rojo',TRUE);
INSERT INTO DRESS (SUBCATEGORY,SEX,BRAND,MODEL,CODE,STOCK,PRICE,AGE,SIZES,COLOR,ENABLED)
    VALUES ('remeras','hombre','nike','A','AB045BB',FALSE,2900,'adultos','21','rojo',TRUE);
INSERT INTO DRESS (SUBCATEGORY,SEX,BRAND,MODEL,CODE,STOCK,PRICE,AGE,SIZES,COLOR,ENABLED)
	VALUES ('remeras','hombre','nike','A','AB045BC',TRUE,2900,'adultos','22','rojo',FALSE);
INSERT INTO DRESS (SUBCATEGORY,SEX,BRAND,MODEL,CODE,STOCK,PRICE,AGE,SIZES,COLOR,ENABLED)
	VALUES ('remeras','hombre','nike','B','AB045BD',TRUE,2900,'adultos','20','azul',FALSE);
INSERT INTO DRESS (SUBCATEGORY,SEX,BRAND,MODEL,CODE,STOCK,PRICE,AGE,SIZES,COLOR,ENABLED)
    VALUES ('pantalones','mujer','47 street','A','AB045CA',TRUE,10000,'jovenes','XXL','jean',TRUE);
INSERT INTO DRESS (SUBCATEGORY,SEX,BRAND,MODEL,CODE,STOCK,PRICE,AGE,SIZES,COLOR,ENABLED)
    VALUES ('buzos','hombre','bando','B','AB045CB',TRUE,9890,'jovenes','L','verde diarrea',FALSE);
INSERT INTO DRESS (SUBCATEGORY,SEX,BRAND,MODEL,CODE,STOCK,PRICE,AGE,SIZES,COLOR,ENABLED)
    VALUES ('boxers','hombre','tommy','A','AB045CC',TRUE,4500,'niños','S','blanco esperanzador',FALSE);


INSERT INTO FRAGRANCE (VOLUMEN,AROMA,ORIGIN_COUNTRY,SUBCATEGORY,SEX,BRAND,MODEL,CODE,STOCK,PRICE,ENABLED)
    VALUES (330,'mierda','Polonia','infantiles','hombre','paco','A','F000',TRUE,1500,TRUE);
INSERT INTO FRAGRANCE (VOLUMEN,AROMA,ORIGIN_COUNTRY,SUBCATEGORY,SEX,BRAND,MODEL,CODE,STOCK,PRICE,ENABLED)
    VALUES (410,'rosas','Argentina','colonias','mujer','karina','A','F001',TRUE,5600,FALSE);
INSERT INTO FRAGRANCE (VOLUMEN,AROMA,ORIGIN_COUNTRY,SUBCATEGORY,SEX,BRAND,MODEL,CODE,STOCK,PRICE,ENABLED)
    VALUES (410,'arbol','Chile','eau de toilette','mujer','prada','B','F002',TRUE,89000,TRUE);