
-- INSERTO LOS ROLES POR DEFECTO QUE VAN A TENER LOS USUARIOS QUE SE LOGUEEN

INSERT INTO ROLES (NAME) VALUES('USER');
INSERT INTO ROLES (NAME) VALUES('ADMIN');

-- INSERTO ALGUNOS USUARIOS POR DEFECTO

INSERT INTO USERS (USERNAME,PASSWORD,EMAIL)
    VALUES ('tiki','pepi90','thiago@gmail.gov');

INSERT INTO USERS (USERNAME,PASSWORD,EMAIL)
    VALUES ('estipy','rabasedas2021','esteban@gmail.edu');

INSERT INTO USERS (USERNAME,PASSWORD,EMAIL)
    VALUES ('admin','admin','example@example.cpp');