-- INSERTO LOS ROLES POR DEFECTO QUE VAN A TENER LOS USUARIOS QUE SE LOGUEEN
INSERT INTO ROLES (NAME) VALUES('USER');
INSERT INTO ROLES (NAME) VALUES('ADMIN');

-- INSERTO ALGUNOS USUARIOS POR DEFECTO
INSERT INTO USERS (USERNAME,PASSWORD,EMAIL)
    VALUES ('tiki','pepi90','thiago@gmail.gov');

INSERT INTO USERS (USERNAME,PASSWORD,EMAIL)
    VALUES ('estipy','rabasedas2021','esteban@gmail.edu');

INSERT INTO USERS (USERNAME,PASSWORD,EMAIL)
    VALUES ('admin','admin','example@example.cpp');

---- INSERTO PRODUCTOS PARA PROBAR
INSERT INTO DRESS (SUBCATEGORY,SEX,BRAND,CODE,STOCK,PRICE,AGE,SIZES,COLOR)
    VALUES ('remeras','hombre','nike','AB045BA',TRUE,2900,'adultos','20','rojo');

INSERT INTO DRESS (SUBCATEGORY,SEX,BRAND,CODE,STOCK,PRICE,AGE,SIZES,COLOR)
    VALUES ('pantalones','mujer','47 street','AB045BB',TRUE,10000,'jovenes','XXL','jean');

INSERT INTO DRESS (SUBCATEGORY,SEX,BRAND,CODE,STOCK,PRICE,AGE,SIZES,COLOR)
    VALUES ('buzos','hombre','bando','AB045BC',TRUE,9890,'jovenes','L','verde diarrea');

INSERT INTO DRESS (SUBCATEGORY,SEX,BRAND,CODE,STOCK,PRICE,AGE,SIZES,COLOR)
    VALUES ('boxers','hombre','tommy','AB045BD',TRUE,4500,'niños','S','blanco esperanzador');

INSERT INTO FRAGRANCE (VOLUMEN,AROMA,ORIGIN_COUNTRY,SUBCATEGORY,SEX,BRAND,CODE,STOCK,PRICE)
    VALUES (330,'mierda','Polonia','infantiles','hombre','paco','F000',TRUE,1500);

INSERT INTO FRAGRANCE (VOLUMEN,AROMA,ORIGIN_COUNTRY,SUBCATEGORY,SEX,BRAND,CODE,STOCK,PRICE)
    VALUES (410,'rosas','Argentina','colonias','mujer','karina','F001',TRUE,5600);

INSERT INTO FRAGRANCE (VOLUMEN,AROMA,ORIGIN_COUNTRY,SUBCATEGORY,SEX,BRAND,CODE,STOCK,PRICE)
    VALUES (410,'arbol','Chile','eau de toilette','mujer','prada','F002',TRUE,89000);